; Copyright 2025 Canonical Ltd.
; See LICENSE file for licensing details.

StylesPath = .vale/styles

Packages = https://github.com/canonical/platform-engineering-vale-package/releases/download/latest/pfe-vale.zip

Vocab = PFE, local


[*.{md,rst}]
BasedOnStyles = PFE

[*.{html,py,png,txt,css,js,json,yaml,yml,toml,cfg,conf,ini,sh,bat,jpg,jpeg,gif,svg,ico,woff,woff2,ttf,eot,map}]

