{
 "title": "WireGuard Gateway Operator (BIRD)",
 "description": "Dashboard for WireGuard Gateway charm (BIRD)",
 "tags": [
  "OSPF",
  "BFD"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Server",
    "query": {
     "query": "label_values(bird_protocol_up,instance)"
    }
   },
   {
    "name": "version",
    "label": "IPv",
    "query": {
     "query": "label_values(bird_protocol_up,ip_version)"
    }
   },
   {
    "name": "tunnel",
    "label": "Tunnel",
    "query": {
     "query": "label_values(bird_bfd_session_up,interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OSPF Status",
   "type": "stat",
   "description": "OSPF establishment status",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bird_ospf_running{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BFD Status",
   "type": "stat",
   "description": "BFD session status",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bird_bfd_session_up{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", interface=~\"$tunnel\"}",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Bird Socket",
   "type": "stat",
   "description": "Result of querying the bird socket",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bird_socket_query_success{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BFD Uptime",
   "type": "stat",
   "description": "Uptime of the BFD session.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bird_bfd_session_uptime_seconds{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", interface=~\"$tunnel\"}",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "OSPF Uptime",
   "type": "stat",
   "description": "Uptime of the OSPF protocol.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bird_protocol_uptime{proto=\"OSPF\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BFD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSPF / BFD",
     "type": "barchart",
     "description": "Comparing Running OSPF with BFD sessions up",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "bird_ospf_running{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
       "legendFormat": "OSPF running"
      },
      {
       "expr": "bird_bfd_session_up{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", interface=~\"$tunnel\"}",
       "legendFormat": "BFD sessions"
      }
     ]
    },
    {
     "title": "BFD Session timeout threshold",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bird_bfd_session_timeout_seconds{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", interface=~\"$tunnel\"}",
       "legendFormat": "{{ interface }}"
      }
     ]
    },
    {
     "title": "BFD hello interval",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bird_bfd_session_interval_seconds{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", interface=~\"$tunnel\"}",
       "legendFormat": "{{ interface }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Neighbor & Interface Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSPF neighbors",
     "type": "timeseries",
     "description": "Total neighbors discovered / adjacent neighbors.",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "bird_ospf_neighbor_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
       "legendFormat": "All neighbors"
      },
      {
       "expr": "bird_ospf_neighbor_adjacent_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
       "legendFormat": "Adjacent neighbors"
      }
     ]
    },
    {
     "title": "preferred routes",
     "type": "stat",
     "description": "Number of preferred routes.",
     "gridPos": { "h": 6, "w": 3, "x": 17, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bird_protocol_prefix_preferred_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", proto=\"OSPF\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OSPF interfaces",
     "type": "stat",
     "description": "Interfaces in the OSPF area.",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bird_ospf_interface_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Route Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSPF Import",
     "type": "timeseries",
     "description": "The rate of imported routes via the OSPF protocol.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_prefix_import_count{proto=\"OSPF\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OSPF Export",
     "type": "timeseries",
     "description": "The rate of exported routes via the OSPF protocol.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_prefix_export_count{proto=\"OSPF\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OSPF filtered",
     "type": "timeseries",
     "description": "The rate of filtered routes via the OSPF protocol.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_prefix_filter_count{proto=\"OSPF\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Update Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming total updates",
     "type": "timeseries",
     "description": "The rate of received updates.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_changes_update_import_receive_count{proto=\"OSPF\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Accepted incoming updates",
     "type": "timeseries",
     "description": "The rate of incoming accepted updates received.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_changes_update_import_accept_count{proto=\"OSPF\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rejected incoming updates",
     "type": "timeseries",
     "description": "The rate of incoming rejected updates received.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_changes_update_import_reject_count{proto=\"OSPF\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outgoing total updates",
     "type": "timeseries",
     "description": "The rate of sent updates.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_changes_update_export_receive_count{proto=\"OSPF\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Accepted outgoing updates",
     "type": "timeseries",
     "description": "The rate of outgoing accepted updates received.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_changes_update_export_accept_count{proto=\"OSPF\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rejected outgoing updates",
     "type": "timeseries",
     "description": "The rate of outgoing rejected updates received.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_changes_update_export_reject_count{proto=\"OSPF\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Withdraw Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming total withdraws",
     "type": "timeseries",
     "description": "Total received withdraws.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_changes_withdraw_import_receive_count{proto=\"BGP\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming accepted withdraws",
     "type": "timeseries",
     "description": "Incoming accepted withdrawals.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_changes_withdraw_import_accept_count{proto=\"BGP\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outgoing total withdraws",
     "type": "timeseries",
     "description": "Total send withdraws.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_changes_withdraw_export_receive_count{proto=\"BGP\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outgoing accepted withdraws",
     "type": "timeseries",
     "description": "Accepted sent withdrawals.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bird_protocol_changes_withdraw_import_accept_count{proto=\"BGP\", juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", ip_version=\"$version\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}