name: Tests

on:
  pull_request:

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      with-uv: true
      self-hosted-runner: false
  integration-tests:
    strategy:
      matrix:
        juju-channel:
          - 3/stable
          - 4/stable
    uses:
      canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      trivy-fs-enabled: true
      trivy-image-config: "trivy.yaml"
      juju-channel: ${{ matrix.juju-channel }}
      provider: 'lxd'
      with-uv: true
      self-hosted-runner: false
  allure-report:
    if: always() && !cancelled()
    needs:
    - integration-tests
    uses: canonical/operator-workflows/.github/workflows/allure_report.yaml@main
